autoupdating the important banner
BUGS-NYU/bugs-nyu.github.io-old pull request #132
Opened 2019-02-26 16:04 UTC by esilverm

Fixes Issue #123.

2019-02-26 16:32 UTC, A1Liu requested changes
Thanks for making this PR! I left a few comments; could you take a look at them? They're just little things, like making sure the JS works w/ the addresses and adding comments to improve readability.

2019-02-26 16:32 UTC, A1Liu commented on index.html
> +          <div id="important"></div>
Could you add a comment denoting that this div is affected by the JS asset file script? I'm worried future contributors might be confused and try to delete it if we don't make it clear that the div gets populated by JS later.

2019-02-26 16:32 UTC, A1Liu commented on assets/js/important.js
> +$.getJSON("../../calendar/data/", (events) => {
isn't this the same thing as `data/`?

2019-02-26 16:32 UTC, A1Liu commented on assets/js/important.js
> +    formatted_date =  `${["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"][final_date.getMonth()]} ${final_date.getDate() + 1}
Can this be done with a format string? Maybe something using the [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) class.

2019-02-26 16:32 UTC, A1Liu commented on index.html
> +    <script src="./assets/js/important.js"></script>
Why is there a dot at the beginning? Have you tested this using `jekyll serve` to ensure this would work in production? I get the feeling like the `src` attribute should be `{{ site.baseurl }}/assets/js/important.js`

2019-02-26 16:37 UTC, esilverm commented on assets/js/important.js
> +$.getJSON("../../calendar/data/", (events) => {
If I am reading your comment correctly, I don't think you can change the file path `../../calendar/data/` to just `data/`. If you do that it won't be able to find the file and will return a 404 error. Correct me if I'm wrong

2019-02-26 16:40 UTC, esilverm commented on assets/js/important.js
> +    formatted_date =  `${["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"][final_date.getMonth()]} ${final_date.getDate() + 1}
Yeah, you are right. Fixed

2019-02-26 16:44 UTC, esilverm commented on index.html
> +    <script src="./assets/js/important.js"></script>
Since the file is locally hosted we don't need to include the entire url in the `src` attribute. The dot is just there to tell us that we are getting to this file from the same directory as the `index.html` file. It is just customary I guess. Let me know if you would like me to keep it

2019-02-26 16:44 UTC, esilverm commented on index.html
> +          <div id="important"></div>
Alright done

2019-02-26 16:46 UTC, esilverm commented on index.html
> +    <script src="./assets/js/important.js"></script>
Actually I'll just remove the dot, but we don't need the `{{ site.baseurl }}`

2019-02-26 16:54 UTC, A1Liu commented on assets/js/important.js
> +$.getJSON("../../calendar/data/", (events) => {
lol oops `calendar/data/` because the site is on the index page, or `{{ site.baseurl }}/calendar/data/` to be more fork-friendly

2019-02-26 16:56 UTC, A1Liu commented on index.html
> +    <script src="./assets/js/important.js"></script>
The `{{ site.baseurl }}` allows people to host the site on their own fork without breaking the site.  without that, something hosted at https://octocat.github.io/bugs-nyu.github.io/ would break.

2019-02-26 17:00 UTC, esilverm commented on assets/js/important.js
> +$.getJSON("../../calendar/data/", (events) => {
The url is relative from the asset file. The problem with only using `{{ site.baseurl }}` is that it is basically just an empty string. Switching to `{{ site.baseurl }}/calendar/data` doesn't work. I think using the `{{ site.baseurl }}/../../calendar/data/` notation is the only way to get the code to work and use the `{{ site.baseurl }}` thing.

2019-02-26 17:06 UTC, esilverm commented on index.html
> +    <script src="./assets/js/important.js"></script>
I changed it to include `{{ site.baseurl }}` for consistency

2019-02-26 17:10 UTC, A1Liu commented on assets/js/important.js
> +$.getJSON("../../calendar/data/", (events) => {
Wait why is it not ok for it to be an empty string? If we're looking relative to the asset file, then `/calendar/data/` should point to an absolute address on the same domain as the file (i.e. bugs-nyu.github.io); in the case that `{{ site.baseurl }}` is empty, this is still true.

2019-02-26 17:13 UTC, esilverm commented on assets/js/important.js
> +$.getJSON("../../calendar/data/", (events) => {
The thing is that `/calendar/data` works but `{{ site.baseurl }}/calendar/data` doesn't work for me.

2019-02-26 17:17 UTC, A1Liu commented on assets/js/important.js
> +$.getJSON("../../calendar/data/", (events) => {
I think you may not have front matter in the document? Or potentially you don't have a `baseurl` attribute set in `_config.yml`.

2019-02-26 17:18 UTC, A1Liu commented on assets/js/important.js
> +$.getJSON("../../calendar/data/", (events) => {
But additionally I'm saying to remove the `/../../` thing

2019-02-26 17:21 UTC, esilverm commented on assets/js/important.js
> +$.getJSON("../../calendar/data/", (events) => {
Yeah I have the `/../../` thing removed. I don't have a reason to set the `baseurl` attribute in my `_config.yml` file

2019-02-26 17:25 UTC, esilverm commented on assets/js/important.js
> +$.getJSON("../../calendar/data/", (events) => {
https://www.w3schools.com/html/html_filepaths.asp

2019-02-26 17:49 UTC, esilverm commented on assets/js/important.js
> +$.getJSON("../../calendar/data/", (events) => {
Ok so i found a Stack Overflow post that kinda explains what you mean. I think that we shouldn't use `/calendar/data/` since it would look too far into the root directory of the forked site. Disregard my last two posts. Since we are using js and it can't figure out what the `{{ site.baseurl }}` thing is, I think the only way we can work around this is to use the `../../` thing

2019-02-26 19:15 UTC, A1Liu commented on assets/js/important.js
> +$.getJSON("../../calendar/data/", (events) => {
No as in, if you add front matter, Jekyll replaces the `{{ site.baseurl }}` with the site's baseurl. That's interesting though, like do we want to replace the `baseurl` stuff with actual relative paths so as to not be tied to Jekyll? Food for thought I guess. Your choice I think; LMK when you're ready and I'll do final checks and merge it.

2019-02-26 19:15 UTC, A1Liu approved these changes

2019-02-26 19:21 UTC, esilverm commented on assets/js/important.js
> +$.getJSON("../../calendar/data/", (events) => {
I think it would be best to replace the `baseurl` stuff for things that it doesn't work for such as JavaScript files. If you would like to keep it consistent for all the files, we could do it for all paths.

2019-02-28 15:57 UTC, esilverm commented
Ok, this is ready to be merged. I made the important.js file fork friendly by using relative paths rather than starting at the root directory. This will make it so if somebody forks the repo the javascript will only look at where it needs to look.

2019-02-28 20:25 UTC, merged