Updated Profiles
BUGS-NYU/bugs-nyu.github.io-old pull request #149
Opened 2020-02-06 17:52 UTC by thatBrian

**PR Type:** Update

**Related #'s:** N/A

Updating Profiles of Eboard Members.

## Description

Updated positions, meta_orders, and descriptions. Removed old members and added new members. 
## Motivation and Context

Required as new semester has arrived.

## Checklist:
- [x] My code follows the [code style of this project][code-style]
- [x] I have read the [**CONTRIBUTING** document][contributing]

[contributing]: https://github.com/BUGS-NYU/bugs-nyu.github.io/blob/master/.github/CONTRIBUTING.md
[code-style]: https://github.com/BUGS-NYU/bugs-nyu.github.io/tree/master/docs/STYLE_GUIDE.md

2020-02-06 18:08 UTC, A1Liu requested changes
Looks good except for a few minor mistakes here and there.

2020-02-06 18:08 UTC, A1Liu commented on _contributors/knguyen.md
> +position: Directory of Communications # Position, only displayed if in eboard
Can you change 'Directory' to 'Director' ?

2020-02-06 18:08 UTC, A1Liu commented on _contributors/jzhang.md
> +position: Directory of Marketing # Position, only displayed if in eboard
Can you change 'Directory' to 'Director' ?

2020-02-06 18:08 UTC, A1Liu commented on _contributors/aliu.md
>  Hi I'm Albert.
Can you change this to "Albert enjoys python scripting and long walks in Central Park. In his work time he majors in Computer Science at CAS."

2020-02-06 18:08 UTC, A1Liu commented on _contributors/aliu.md
>  Hi I'm Albert.
I changed my bio to "Hi I'm Albert" when I was refactoring a while ago and forgot to change it back.

2020-02-06 18:08 UTC, A1Liu commented on _contributors/dtran.md
> +type: alum
Could you do the same thing for Veena and Shelly?

2020-02-06 18:08 UTC, A1Liu commented on _contributors/slin.md
>  position: Vice Project Lead
Could you change this to Vice President?

2020-02-07 03:15 UTC, thatBrian commented
Fixed, please check. @A1Liu

2020-02-07 15:00 UTC, A1Liu requested changes
Just the one thing and I'll approve.

2020-02-07 15:00 UTC, A1Liu commented on _contributors/aliu.md
> +Can you change this to "Albert enjoys python scripting and long walks in Central Park. In his work time he majors in Computer Science at CAS."
Please remove the "Can you change this" and the quotations.

2020-02-07 15:51 UTC, merged