Add Contributors Image
BUGS-NYU/bugs-nyu.github.io-old pull request #204
Opened 2021-02-28 07:11 UTC by yuchenliu15

![image](https://user-images.githubusercontent.com/43976449/109410575-97705c80-7950-11eb-8084-4a651ea5fecd.png)

mobile:
![image](https://user-images.githubusercontent.com/43976449/109410585-ac4cf000-7950-11eb-8497-fc08d58882c5.png)

2021-02-28 07:14 UTC, yuchenliu15 commented on src/pages/contributors.js
> +    margin-left: 0;
a bit of a hack to make the image center bc the profile pictures inside the image aren't centered. 
is there a better way? :eyes:

2021-02-28 15:29 UTC, Kn99HN commented on src/pages/contributors.js
> +    margin-left: 0;
Evan might have a better way. I couldn't figure out a better way to do this either

2021-02-28 15:35 UTC, Kn99HN requested changes
The picture looks bit pixelated but we can't really do anything else about that. Other than that, I like it! Just some minor changes

2021-02-28 15:35 UTC, Kn99HN commented on src/pages/contributors.js
> +              <ContributorsImage />
I think it looks a bit cramped. Can we add some space between the image and the Timeline?

2021-02-28 15:35 UTC, Kn99HN commented on src/pages/contributors.js
>              <TimelineContainer>
Can you remove the margin for the `<TimelineContainer>` since now we want it to be in the center?

2021-02-28 16:57 UTC, esilverm commented on src/pages/contributors.js
> +    margin-left: 0;
It shouldn't be too hard to make our own one. Getting the contributors is simple enough:

https://api.github.com/repos/BUGS-NYU/bugs-nyu.github.io/contributors

The avatar_url is included for all users so we should be able to make a component that does the same thing.

2021-02-28 20:14 UTC, yuchenliu15 commented on src/pages/contributors.js
> +    margin-left: 0;
@esilverm oh yea that's great!

2021-03-06 18:33 UTC, yuchenliu15 commented
@esilverm thanks for the solution!

2021-03-06 18:33 UTC, yuchenliu15 commented
this linter is so hard to please :disappointed:

2021-03-06 19:48 UTC, Kn99HN approved these changes
LGTM!

2021-03-06 20:44 UTC, merged

2021-03-06 21:05 UTC, esilverm reviewed
Two small suggestions. Just change these and we can merge.

2021-03-06 21:05 UTC, esilverm commented on src/pages/contributors.js
> +      }));
We can use object destructuring to make this a little bit prettier

```js
data.map(({avatar_url, html_url, login}) => ({
  image: avatar_url,
  url: html_url,
  name: login,
})

2021-03-06 21:05 UTC, esilverm commented on src/pages/contributors.js
> +    ));
This would read better as

```js
contributors.map({name, url, image}) => (
  <a key={name} href={url}>
    <Image alt={name} contributor={image} />
  </a>
));
```

2021-03-06 21:07 UTC, esilverm commented
oof i was too late lol

2021-03-06 22:58 UTC, yuchenliu15 commented
@esilverm uhh my bad